### ISSUE TITLE
Не видит файлы 

### ISSUE THREAD

**Issue by udiFi** [vvip-68/LedPanelWiFi#106]

**Comment by vvip-68** [comment]
Загрузите туда файлы. Сейчас эти папки пустые.

**Comment by udiFi** [comment]
![image](https://github.com/user-attachments/assets/c59f245f-694d-4469-8b27-5272c562bba7)

**Comment by vvip-68** [comment]
Вероятно у вас либо новая ArduinoIDE 2.x.x - ее плагины временами глючат и не могут создать пакет для загрузки. Вроде не линукс - на линуксе подобные проблемы были.  Если с 10 попыток загрузить не получится - поставьте Arduino IDE 1.8.19 и ее плагины для загрузки в файловую систему. Они вроде не глючили ни разу.
Ну или используйте отдельные утилиты типа espTools - но я их не пользовал - ничего подсказать не могу.

Вот тут человек как-то решил проблему - свяжитесь с ним.
https://github.com/vvip-68/LedPanelWiFi/issues/102

**Comment by udiFi** [comment]
1.8.19, загружал и с платформио и онлайн. Зато на счет красной ошибки узнал https://github.com/me-no-dev/arduino-esp32fs-plugin/issues/3#issuecomment-337079574

**Comment by vvip-68** [comment]
Так это понятно, что SPIFFS - ограничение 32
Только там не SPIFFS используется - а LittleFS.
И почему плагин готовит файлы как будто под SPIFFS а не под LittleFS - загадка.
И почему другие плагины (или ээти время от времени) - нормально упаковывают данные файлы...
Вот у меня такая ошибка ни разу не встречалась.
У других - довольно часто - не вы первый...
Они заливали из под 1.8.19 - заливалось. Под 2.3.3 - не всегда.

**Comment by udiFi** [comment]
"И почему плагин готовит файлы как будто под SPIFFS а не под LittleFS - загадка." - сам не знаю, может глянуть на скрины что в проекте


https://github.com/vvip-68/LedPanelWiFi/blob/main/setitngs-esp32.png

**Comment by vvip-68** [comment]
Эти скрины отражают то, что работает у меня, что проверено.
Можете выбрать - там вариант есть с FAT. Может взлетит. Только все равно файловая система - LittleFS.
