### ISSUE TITLE
Неправильная адресация

### ISSUE THREAD

**Issue by lugadin** [vvip-68/LedPanelWiFi#108]
Два куска ленты по 126 диодов. Подключены к двум пинам. Наклеено 2 окна по ширина 14, высота 9 - змейкой (снизу влево). 
При рисовании, если закрашивать крайний левый/правый ряд, диоды горят:

0 0 0 0 0 0 0 0 0 0 0 0 1 1 
0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 1 1
0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 1 1
0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 1 1
0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 1

![photo_2024-12-25_23-54-00](https://github.com/user-attachments/assets/ba744fd7-8a59-43e9-a769-79d88c06f2ff)
![photo_2024-12-25_23-53-58](https://github.com/user-attachments/assets/af007561-987c-4ec3-a729-c5ff23051c60)

Фото из комнаты
![photo_2024-12-25_23-53-56](https://github.com/user-attachments/assets/53404f1e-6aa8-4e18-836f-1ca9943d2928)

**Comment by vvip-68** [comment]
Неправильная настройка матрицы. Разбирайтесь как реально у вас что подключено. Или "странная" лента с китайской адресацией. По фото видно, что если ленту "протянуть на один диод вправо - крайний у рамы диод уйдет вниз, соседний подтянется к раме и в результате получится заполненный полностью один правый столбец. Что соответствует рисунку в приложении.
