### ISSUE TITLE
Не получается установить библиотеку

### ISSUE THREAD

**Issue by Mihger** [vvip-68/LedPanelWiFi#109]
При распаковке архива с библиотекой ESPAsyncWebServer.zip (из папки "для esp8266 core 3.1.2 FastLed 3.6.0")возникает ошибка распаковки, пишет файл библиотеки поврежден. Если устанавливать библиотеку через Arduino IDE так же возникает ошибка.

**Comment by vvip-68** [comment]
Обновите свой архиватор. Видимо он у вас какой-то древней версии.
С библиотекой ESPAsyncWebServer взятой не из папки проекта с вероятностью 80% ничего работать не будет.
