### ISSUE TITLE
говорящие часы

### ISSUE THREAD

**Issue by bdu1977** [vvip-68/LedPanelWiFi#12]
в папке с проектом есть папка sounds там есть ссылка на скачивание звуков для будильника, и там же говориться о говорящих часах, а где найти данную настройку?

**Comment by vvip-68** [comment]
Что-то у меня нет в этом проекте никаких папок и ссылок на говорящие часы...
В прошлых проектах было упоминание - но оно так и осталось нереализованным. Сначала из за нехватки времени, потом из за пришедшего понимания, что это нафиг никому не нужно, и в первую очередь - мне.
Поэтому в этой версии я вроде как все упоминания про говорящие часы удалил... Неужели где-то пропустил?
К тому же уже есть прошивки и с говорящими часами и с огромным количеством всяких эффектов. К чему повторяться?
