### ISSUE TITLE
макроc {P}

### ISSUE THREAD

**Issue by bdu1977** [vvip-68/LedPanelWiFi#13]
придумал как протестировать срабатывание бегущей строки с разными макросами. вот и появился еще вопрос. меня долго интересовал макрос {P} как он срабатывает и как отображается, поскольку я никогда не мог присутствовать в данный момент около матрицы. строка отображается как обычно и то при условии, что она включится в определенный промежуток. в итоге
{B#000000}{C#000002}До Нового года осталось{P01.01.****#Y#60#60}
на матрице отображается просто бегущая строка с отсчетом времени. а можно запрограмировать ее так,  не зависимо от того какой сейчас эффект работает или же на матрице в это время идет другая строка, что бы она принудительно запускалась, пробегала фраза "до нового года осталось" и далее что бы только цифры (не бегали, а стояли на месте как часы,  отсчитывали секунды, ну а далее как обычно, поздравление или что было запрограмировано.
мне кажется, что этот макрос лучше будет в таком виде смотреться.

**Comment by vvip-68** [comment]
Ну, насколько я понимаю, данный макрос включится  31.12.**** года в 23:59, далее целую минуту будет непрерывно отображаться строка, содержащая макрос, затем 01.01.**** в 0:00 будет отображаться целую минуту строка Y.
Запускаться должна принудительно на любом эффекте (про замену текущую другую строку - не помню, но в любом случае эта строка должна тогда запуститься сразу после текущей, если она есть, а обычно строка бежит не более 10 секунд (в зависимости от ее длины и скорости прокрутки)).

Мне кажется подобное отображение не совсем корректным - что если не увидел, как пробегала строка фразы, а потом просто какой-то непонятный обратный отсчет...

В любом случае - исходный код проекта открытый - вы можете запрограммировать алгоритм, чтобы отображалось именно так, как вам нужно.
