### ISSUE TITLE
неинициализированная переменная при расширении макро

### ISSUE THREAD

**Issue by vortigont** [vvip-68/LedPanelWiFi#34]
https://github.com/vvip-68/LedPanelWiFi/blob/13cb8ccd429ab6c85034935dbe0440f0c09e82d5/firmware/LedPanelWiFi_v1.14/pictures.ino#L112-L115

макросы которые "укорачивают" писанину могут скрывать проблему
если раскрыть макрос в вышеприведенном коде получится
`for(int j = j; j < MAX_FRAMES_COUNT; j++){}` т.е. j будет инициализированна сама собой. Там может оказаться что угодно, может ноль, а может случайное значение.
Что на самом деле должно быть в коде из контекста не оч. понятно.

**Comment by vvip-68** [comment]
Исправлено
