### ISSUE TITLE
Connection lost - WEB

### ISSUE THREAD

**Issue by Andriejus** [vvip-68/LedPanelWiFi#58]
Hi. Sometimes im loosing connection on WEB and i get these messages in serial port. Could someone give me advice what could be wrong? 
ESP32 WROOM.
P.S. I undestand Russian language.

![Screen Shot 2024-02-01 at 16 13 50](https://github.com/vvip-68/LedPanelWiFi/assets/38490002/d5cfa9e3-8146-4025-9773-12f646debbf1)

**Comment by vvip-68** [comment]
Как выяснилось в ходе экспериментов в последнее время, лично у меня, постоянные Connection Lost в  Web-интерфейсе случились из за неверной библиотеки ESPAsyncWebServer - она у меня стояла не из папки проекта, а какая-то экспериментально-случайная. Поменял на библиотеку из папки проекта - все проблемы с потерей соединения ушли.
Какая библиотека стоит у вас?

Все сообщения в логе "Too many messages" как правило (если не появляются постоянно) значения не имеют. При первой попытки соединиться с контроллером веб-страница шлет одноразово довольно много запросов и чать из них не успевает обрабатываться и переполняют очередь (с выводом в лог данного сообщения). Но Web-страница довольно умна, чтобы не получив ответ на запрос - отправить его повторно. То есть через короткий промежуток времени все данные, необходимые для работы WebUI все равно будут получены.

26.10.2024 я обновил версию в репозитории - в ней исправлено получение погоды с серверов Yandex.
Попробуйте ее - может быть и эта проблема тоже как-нибудь уйдет...
