### ISSUE TITLE
нехватки памяти ?

### ISSUE THREAD

**Issue by Andriejus** [vvip-68/LedPanelWiFi#60]
Hi, is everything OK here with memory? What "FM" means? :)

![Skjermbilde 2024-02-15 17 50 42](https://github.com/vvip-68/LedPanelWiFi/assets/38490002/3d53194a-3a60-462e-bc4e-c1544fd33603)

![Skjermbilde 2024-02-15 17 50 42](https://github.com/vvip-68/LedPanelWiFi/assets/38490002/d81541d0-af47-411c-815b-7f900bc47be4)

**Comment by vvip-68** [comment]
"FM: is "Free Memory' - getting value iia call of ESP.getFreeHeap(); "Max" is size of maximal available continuous block of memory in Heap - ESP.getMaxAllocHeap()

According to log you have enough memory for sketch needs
