### ISSUE TITLE
Compilation error: 'LINEARBLEND_NOWRAP' was not declared in this scope

### ISSUE THREAD

**Issue by hhrhhr** [vvip-68/LedPanelWiFi#65]
Делаю всё по инструкции, при компиляции столкнулся с ошибкой, указанной в названии.
Поиск по исходникам выдаёт использование макроса LINEARBLEND_NOWRAP только в файле \firmware\LedPanelWiFi_v1.14\effects2.ino, но нигде нет определения этого макроса.

https://github.com/vvip-68/LedPanelWiFi/blob/3188ed6ae6a00728cfecc67b09c90ecbc58be045/firmware/LedPanelWiFi_v1.14/effects2.ino#L433-L434

**Comment by hhrhhr** [comment]
> не та версия FastLED используется

[Из вики](https://github.com/vvip-68/LedPanelWiFi/wiki/Пошаговая-инструкция-подготовки-среды-и-сборка-проекта):
_A строке поиска наберите "FastLED" Выберите блок "FastLED by Daniel Garcia"
Выберите версию библиотеки **3.5.0**_

Из README.MD
_Данный проект рассчитан на работу с версиями ядра плат ESP8266 версии 3.1.2, ESP32 версии 1.0.6 и библиотеки FastLED версии **3.5.0**;_

Из FAQ:
_**О**: Это стандартная библиотека для FastLED для управления адресными светодиодами. Идите в менеджер библиотек и установите ее. Версию библиотеки выбирайте **3.5** или 3.4;_

**Comment by vvip-68** [comment]
Возможно в readme упустили, не актуализировали...
Думаю стоит ориентироваться на это:
![image](https://github.com/user-attachments/assets/d4088213-1226-4d91-ae5c-c6809bc4b3cb)

**Comment by hhrhhr** [comment]
Да, с FastLED 3.6 сборка прошла. Однако в версиях ниже 3.6 макроса LINEARBLEND_NOWRAP не существует, то есть комментарии про 3.4-3.5 уже не актуальны (без правки кода effects2.ino).

**Comment by vvip-68** [comment]
Да, не актуальны... Надо будет как-нибудь поправить...
