### ISSUE TITLE
Перестала работать погода от Яндекса.

### ISSUE THREAD

**Issue by didos06** [vvip-68/LedPanelWiFi#66]
У Яндекса что-то поменялось что-ли? Погоду перестала панель показывать. Два устройства в виде часов с погодой использую, ни одно погоду не показывает от Яндекса. Open weather работает.

**Comment by vvip-68** [comment]
Да, поменялось. Он перестал отдавать погоду по HTTP. Теперь хочет исключительно HTTPS.
Работать с HTTPS я не умею. Если у кого есть пример рабочего кода для получения данных по HTTPS именно от Яндекса (и инструкция как настроить) - пишите, поправим.
