### ISSUE TITLE
Обновление

### ISSUE THREAD

**Issue by bulava92** [vvip-68/LedPanelWiFi#70]
добрый день
попытался установить данную прошивку взамен старой - постоянно ругается на настройки в 49 строке. пересмотрел всё что можно, ничего не нашел, в чем дело может быть? вообще ругается на отсутствие файла

старая прошивка накатывается без проблем, но через несколько дней после использования начинает хаотично перезагружаться каждые 5-60 минут

**Comment by vvip-68** [comment]
Вы полагаете, что без текста ошибки вам кто-нибудь ответит что-нибудь вразумительное? Не думаю...
Обычно либо прошивка сразу работает с глюками и так-сяк, либо работает. А тут без дополнительной информации - да кто ж его знает то?

Вообще, эта прошивка все еще в стадии экспериментальной и не рекомендуемой. Ее веб-интерфейс работает нестабильно и на разных платах (и в разных конфигурациях) зачастую по-разному. От более менее-стабильной работы, до постоянных отваливания связи. Так что опять не рекомендую. На свой страх и риск.

Перезагружаться хаотично может если включена погода, потому что по факу оно больше не работает. Яндекс перестал отдавать погоду по протоколу http еще 28 июля,  а OpenWeastherMap - стал отдавать ее один раз из трех. И когда прошивка не может получить погоду - оно периодически перезагружается. Попробуйте отключить погоду вообще.
