### ISSUE TITLE
ошибка при компиляции

### ISSUE THREAD

**Issue by Den19081981** [vvip-68/LedPanelWiFi#76]
вот такая ошибка в строках 433-434 в effekts2.ino,как поправить

if      (firework[i].the_figMode == 0) drawCircleBlend    (firework[i].the_figX, firework[i].the_figY, firework[i].the_figSize, ColorFromPalette( myRainbow_p, firework[i].the_figHue, (firework[i].the_figSize > firework[i].the_figSizeMax / 2) ? effectBrightness - effectBrightnessFaded : effectBrightness, LINEARBLEND_NOWRAP));
      else if (firework[i].the_figMode == 1) drawSnowflakesBlend(firework[i].the_figX, firework[i].the_figY, firework[i].the_figSize, ColorFromPalette( myRainbow_p, firework[i].the_figHue, (firework[i].the_figSize > firework[i].the_figSizeMax / 2) ? effectBrightness - effectBrightnessFaded : effectBrightness, LINEARBLEND_NOWRAP));

**Comment by vvip-68** [comment]
Установить вместо случайной рекомендуемую версию FastLED/ Рекомендуемая - 3.6.0
