### ISSUE TITLE
Долой EEPROM если есть SD-карта.

### ISSUE THREAD

**Issue by hhrhhr** [vvip-68/LedPanelWiFi#86]
Вычитал пугательные вещи про эмуляцию EEPROM во флеше. Пугает меня низкий ресурс самой флешки и довольно частый, судя по журналу, сброс значений EEPROM в память, то есть перезапись.

Как насчёт подумать про отказ от эмуляции в случае наличия SD-карточки? И веб-интерфейс туда и настройки, благо что сохранение вручную нарисованных картинок на SD-карточку уже реализовано.

**Comment by vvip-68** [comment]
Нахожу это довольно бессмысленным и имеющим массу минусов, особенно в части переноса Web-интерфейса.
Сдохла карточка  или вынули и всё - устройство недоступно, а при некоторых моментах и вообще не запускается.
По моему личному опыту SD карточки дохнут гораздо чаще. Просто воткнутая в телефон карточка сдыхает уже через полгода-9 месяцев. Хотя типа просто стоит в телефоне.

"... довольно частый, судя по журналу, сброс значений EEPROM в память..."
Насколько частый? И пишутся в память настройки - только после их изменения, в большинстве случаем через 30 сек после изменения последней. Ну или сразу после изменения для критических значений. Причем в память, а не в эмуляцию файловой системы. Настройки можно сохранять на карточку в бэкап-файл. Сдохнет контроллер -перепрошьете новый и восстановите настройки из резервной копии.

Заявленный производителем ресурс перезаписи eeprom - 10 тыс записей. Что и как часто вы пишете в файловую систему контроллера? Насколько при такой частоте записи хватит ресурса памяти? Считали? У меня гирлянды уже лет 5 работают без нареканий. И думаю еще лет на 20 хватит. Стоимость микроконтроллера - копейки. Сдохнет - поменяю. Ничего ценного там не хранится.

Обычно записывается состояние вкл/выкл. Ну, пару раз в день. 5000 дней - это 12-13 лет. при круглогодичной эксплуатации. А если считать, что гирлянда работает пару  месяцев в году - то ресурса хватит на 120 лет... Да даже если на 60 - этого за глаза...

Контроллеры, которые под разработку - постоянно перезаписываются при обновлении прошивки. Тысячами раз. И живы.
Так что - всё это довольно бессмысленно.

Впрочем - код открытый. Каждый волен делать изменения, которые ему нужны.

**Comment by hhrhhr** [comment]
> Сдохла карточка или вынули и всё - устройство недоступно

Пример очень надуманный, типа а если молотком долбануть, то и вовсе устройство можно выкинуть.

>  SD карточки дохнут гораздо чаще.

У меня в телефоне стоит самсунг, который пережил предыдущие 5 телефонов, лет 8 как использовалась сначала как замещение памяти, потом просто для "съёмный накопитель". В регистраторе уже пятый год трудится не самая дорогая Smartbuy, тоже пережила пару регистраторов и 20 часов в неделю непрерывной работы. Так-то да, если покупать карточки с ценой контроллера, то их не напасёшься. С другой стороны, карты меньше 1 Гб нынче меньше 100 руб, что в разы дешевле всяких D1 mini clone.

> Что и как часто вы пишете в файловую систему контроллера?

Вообще-то это вам виднее, что и как часто пишется. Я же вижу, что при сбросе питания гирлядна почти всегда запускается на прерванном эффекте, то есть каждая смена по таймеру или вручную - запись.

Ресурс в 10000 перезаписей для флешек указан для фирменных модулей, а в то, чем торгуют на Али, пихают безымянные чипы с неизвестным ресурсом. Далее, в любой SD-карте есть свой контроллер с функцией выравнивания износа, при стандартном использовании он сам выбирает ячейки для текущей записи. Прошивка же в текущем состоянии перезаписывает "EEPROM" в одно и то же место во флеш-памяти, причём сразу целым блоком.
Нет желания возиться с переделкой под SD — уже есть же LittleFS, с выравниваем износа и устойчивостью к сбоям по питанию. Будет писать равномерно по всему доступному объёму флеша, а не долбить одни и теже 4 Кб.

> код открытый. Каждый волен делать изменения, которые ему нужны.

Ну да, даёшь кучу форков с минорными фичами, ибо автору лениво и бессмысленно ;)
