### ISSUE TITLE
результаты cppcheck

### ISSUE THREAD

**Issue by hhrhhr** [vvip-68/LedPanelWiFi#88]
Понимаю, что к статическим анализаторам стоит относиться очень предвзято, но некоторые предупреждения вызвали у меня вопросы.

_CWE-570:Logical conjunction always evaluates to false_
https://github.com/vvip-68/LedPanelWiFi/blob/7bdd30fce080eb90364f669dcbf5f79d22f6df8f/firmware/LedPanelWiFi_v1.14/eeprom.ino#L664
То же самое в строках 676, 724, 736. Здесь перепутаны AND и OR или это такой хитрый хак?

_CWE-398:Comparison of a boolean expression with an integer other than 0 or 1._
https://github.com/vvip-68/LedPanelWiFi/blob/7bdd30fce080eb90364f669dcbf5f79d22f6df8f/firmware/LedPanelWiFi_v1.14/setters.ino#L269-L273
Приведение к булеву типу числового значения и его сравнивание - условие практически никогда не будет ложным. 

CWE-398:Identical inner 'if' condition is always true.
https://github.com/vvip-68/LedPanelWiFi/blob/7bdd30fce080eb90364f669dcbf5f79d22f6df8f/firmware/LedPanelWiFi_v1.14/utility.ino#L107-L116
Лишняя дублирующая проверка, вроде как.

CWE-570:Condition 'err' is always false
https://github.com/vvip-68/LedPanelWiFi/blob/7bdd30fce080eb90364f669dcbf5f79d22f6df8f/firmware/LedPanelWiFi_v1.14/effects.ino#L2523-L2528
Как оно вообще работает, если условие всегда ложно?

**Comment by vvip-68** [comment]
1 - да, там "или" должно быть
2 - там не bool, там uint8_t должно быть
3 - да, там внутренний if - лишний
4 - err там вообще лишний. 

Так err -по или, и ни на что не влияет. А вот часть noise3d == NULL - вполне себе нормально должно срабатывать
Спасибо за бдительность!
