### ISSUE TITLE
не удается скомпелировать

### ISSUE THREAD

**Issue by Dilkins85** [vvip-68/LedPanelWiFi#94]
не идет компиляция, уже все библиотеки перепробовал
вот что выдает 

In file included from /Users/vitalijbalcezak/Desktop/LedPanelWiFi_v1.14/a_def_hard.h:631,
                 from /Users/vitalijbalcezak/Desktop/LedPanelWiFi_v1.14/LedPanelWiFi_v1.14.ino:355:
/Users/vitalijbalcezak/Desktop/LedPanelWiFi_v1.14/a_def_lang.h:39:6: warning: multi-character character constant [-Wmultichar]
   39 | #if (LANG == 'RUS')
      |      ^~~~
/Users/vitalijbalcezak/Desktop/LedPanelWiFi_v1.14/a_def_lang.h:39:14: warning: multi-character character constant [-Wmultichar]
   39 | #if (LANG == 'RUS')
      |              ^~~~~
In file included from /Users/vitalijbalcezak/Desktop/LedPanelWiFi_v1.14/a_def_hard.h:631,
                 from /Users/vitalijbalcezak/Desktop/LedPanelWiFi_v1.14/LedPanelWiFi_v1.14.ino:355:
/Users/vitalijbalcezak/Desktop/LedPanelWiFi_v1.14/a_def_lang.h:343:6: warning: multi-character character constant [-Wmultichar]
  343 | #if (LANG == 'ENG')
      |      ^~~~
/Users/vitalijbalcezak/Desktop/LedPanelWiFi_v1.14/a_def_lang.h:343:14: warning: multi-character character constant [-Wmultichar]
  343 | #if (LANG == 'ENG')
      |              ^~~~~
/Users/vitalijbalcezak/Desktop/LedPanelWiFi_v1.14/a_def_lang.h:638:6: warning: multi-character character constant [-Wmultichar]
  638 | #if (LANG == 'ESP')
      |      ^~~~
/Users/vitalijbalcezak/Desktop/LedPanelWiFi_v1.14/a_def_lang.h:638:14: warning: multi-character character constant [-Wmultichar]
  638 | #if (LANG == 'ESP')
      |              ^~~~~
/Users/vitalijbalcezak/Desktop/LedPanelWiFi_v1.14/a_def_lang.h:933:6: warning: multi-character character constant [-Wmultichar]
  933 | #if (LANG == 'LAT')
      |      ^~~~
/Users/vitalijbalcezak/Desktop/LedPanelWiFi_v1.14/a_def_lang.h:933:14: warning: multi-character character constant [-Wmultichar]
  933 | #if (LANG == 'LAT')
      |              ^~~~~
In file included from /Users/vitalijbalcezak/Documents/Arduino/libraries/FastLED/src/FastLED.h:75,
                 from /Users/vitalijbalcezak/Desktop/LedPanelWiFi_v1.14/a_def_hard.h:652,
                 from /Users/vitalijbalcezak/Desktop/LedPanelWiFi_v1.14/LedPanelWiFi_v1.14.ino:355:
/Users/vitalijbalcezak/Documents/Arduino/libraries/FastLED/src/fastspi.h:157:23: note: '#pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output'
  157 | #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
. Variables and constants in RAM (global, static), used 44176 / 80192 bytes (55%)
║   SEGMENT  BYTES    DESCRIPTION
╠══ DATA     1856     initialized variables
╠══ RODATA   9448     constants       
╚══ BSS      32872    zeroed variables
. Instruction RAM (IRAM_ATTR, ICACHE_RAM_ATTR), used 61647 / 65536 bytes (94%)
║   SEGMENT  BYTES    DESCRIPTION
╠══ ICACHE   32768    reserved space for flash instruction cache
╚══ IRAM     28879    code in IRAM    
. Code in flash (default, ICACHE_FLASH_ATTR), used 684408 / 1048576 bytes (65%)
║   SEGMENT  BYTES    DESCRIPTION
╚══ IROM     684408   code in flash

**Comment by vvip-68** [comment]
А что в вашем понимании должно выводится, когда компиляция "идёт"?
Появиться надпись - "Уважаемый Dilkins85, все прошло успешно"?
