### ISSUE TITLE
настройка цвета светодиода

### ISSUE THREAD

**Issue by Dilkins85** [vvip-68/LedPanelWiFi#95]
возникла проблема что две гирлянды имеют разные светодиоды с разным расположением цветов, как можно выровнить цвет общего полотна, я так понял можно создать карту сегментов но как к сегментам назначить расположение цветов?

**Comment by vvip-68** [comment]
https://github.com/vvip-68/LedPanelWiFi/wiki/FAQ#в-порядок-цветов---две-разных-ленты-с-разным-порядком-цветов
