### ISSUE TITLE
Проблема с эффектами

### ISSUE THREAD

**Issue by barsik1986** [vvip-68/LedPanelWiFi#97]
При переключении эффекта остается старый и мигает первый светодиод, попытки поменять библиотеку как описано в описании результата не дало. Помогите!!!

**Comment by vvip-68** [comment]
Все способы решения описаны в основном файле в начале в комментарии и в wiki проекта (FAQ). Других рецептов нет. Вроде бы в версии 1.14.2024.1210 и выше данная проблема максимально устранена. По крайней мере у меня проблема перестала встречаться.

**Comment by barsik1986** [comment]
Спасибо, буду пробовать дальше.
