### ISSUE TITLE
косяки при USE_WEATHER 0

### ISSUE THREAD

**Issue by hhrhhr** [vvip-68/LedPanelWiFi#99]
ESP8266, core 3.1.2, IDE 1.8.19, всё остальное как полагается:
```
...\LedPanelWiFi-main\firmware\LedPanelWiFi_v1.14\a_main.ino: In function 'void parsing()':
a_main:1957:12: error: 'set_ShowTempTextProps' was not declared in this scope; did you mean 'getShowTempTextProps'?
 1957 |            set_ShowTempTextProps(intData[2]);
      |            ^~~~~~~~~~~~~~~~~~~~~
      |            getShowTempTextProps

```
Полагаю, это после добавления значков градусов и прочих фаренгейтов в  458c3cf58e492dbd0f6a3000b014244fa0455d5f.

Сходу "исправил" обернув этот блок
https://github.com/vvip-68/LedPanelWiFi/blob/6347fe3fade61a260eb7b40cd8d629353b506eb1/firmware/LedPanelWiFi_v1.14/a_main.ino#L1956-L1958
в `#if (USE_WEATHER == 1) ... #endif` (так как определения этих функции уже обёрнуты), но если из веб-интерфейса придёт такая команда, то не проверял.

**Comment by vvip-68** [comment]
Спасибо. Действительно. Поправлю. 
Если USE_WEATHER == 1 и придет из интерфейса - все ОК.
Если USE_WEATHER == 0 - оно даже не скомпилится, т.к. функция неизвестна.
